version = 1

[[analyzers]]
name = "csharp"

[[analyzers]]
name = "rust"

  [analyzers.meta]
  msrv = "1.30.0"

[[analyzers]]
name = "php"

[[analyzers]]
name = "java"

  [analyzers.meta]
  runtime_version = "11"

[[analyzers]]
name = "shell"

[[analyzers]]
name = "javascript"

[[analyzers]]
name = "ruby"

[[analyzers]]
name = "go"

  [analyzers.meta]
  import_root = "github.com/eshaan-test-org/test-monorepo/packages/gigarepo/go"

[[analyzers]]
name = "python"

  [analyzers.meta]
  runtime_version = "3.x.x"